### ISSUE TITLE
How To Login using an exness trading account? trading server: `mt4real16.exness.com:443`

### ISSUE THREAD

**Issue by matthewM-sofsafe** [CoeJoder/metatrader4-client-python#3]
I can't seem to figure out how to use this client. Can you please show more examples?

**Comment by CoeJoder** [comment]
Hi @matthewM-sofsafe, have you setup the server-side using the sister project [MetaTrader 4 Server](https://github.com/CoeJoder/metatrader4-server)?  If you give me some more information about your setup, I might be able to help.
